### ISSUE TITLE
Little question about the finished example

### ISSUE THREAD

**Issue by figurantpp** [cfsamson/books-futures-explained#38]
The finished example has some comments delimiting the future implementation, the executor, and the reactor code, which makes it easy to reason about what each code does.

but why is the MyWaker code (lines 63-98) categorized as future implementation code, and not executor code?

Side note: Thank you for this book, it has everything I wanted to understand, explained very didactically and it ended most of, if not all my doubts on Futures.

**Comment by cfsamson** [comment]
That's a good question. I wanted to keep `Future` and `Waker` together since I view them as the "glue" between the Reactor and the Executor parts of a runtime.

I realize that there is a strong argument to put the `Waker` _implementation_ with the Executor since they're so closely tied together, but I wanted to emphasize what's part of the Rust Language (Waker and Future) and what's not (the runtime specifics). If it creates confusion I might have to change it :) But at least this was the idea behind it.

>Side note: Thank you for this book, it has everything I wanted to understand, explained very didactically and it ended most of, if not all my doubts on Futures.

That makes me really happy to hear! Thanks for letting me know!

**Comment by figurantpp** [comment]
>  I wanted to emphasize what's part of the Rust Language (Waker and Future) and what's not (the runtime specifics). 
Thanks, it makes sense when explained like this, it wasn't very clear at first glance. It would be nice to have side note explaining this detail though.

**Comment by cfsamson** [comment]
I'll leave this issue open and add a note abut it when I have some time.
